# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice
app: serverless-shop1
org: rahatekars
service: serverless-shop1
# Configuration variables
custom:
  webpack:
      includeModules:
        packagePath: 'package.json'
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  # profile: personal
  region: eu-west-1
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey} # Stripe secret API key

# The `functions` block defines what code to deploy
functions:
#   createCharge:
#     handler: functions/createCharge.handler
#     # The `events` block defines how to trigger the handler.createCharge code
#     events:
#       - http:
#           path: charges
#           method: post
#           cors: true
  fetchProducts:
    handler: functions/fetchProducts.handler
    events:
      - http:
          path: products
          method: get
          cors: true
          
  fetchSKUs:
    handler: functions/fetchSKUs.handler
    events:
      - http:
          path: skus
          method: get
          cors: true

  createCharge:
    handler: functions/createCharge.handler
    events:
      - http:
          path: charges
          method: post
          cors: true